mozilla_blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path("", include("story.urls")),
    path('admin/', admin.site.urls),
    # adding path to the story
    # redirecting blog path

]

mozilla_blog/story/urls.py
from django.urls import path
from . import views

app_name = "story"
urlpatterns = [
    path("", views.index, name="index"),
    path("blog/", views.index, name="index"),
    path("blog/<int:pk>", views.BlogPostDetailView.as_view(), name="blog-detail"),
    path("blog/blogs/", views.BlogPostListView.as_view(), name="blogs"),
    path("blog/blogger/<int:pk>", views.BloggerDetailView.as_view(), name="blogger-detail"),
    path("blog/bloggers/", views.BloggerListView.as_view(), name="bloggers"),
    # path("blog/comments/", views.BloggerListView.as_view(), name="bloggers"),
]

mozilla_blog/story/models.py
from django.db import models
from django.utils import timezone
from django.shortcuts import reverse


class Blogger(models.Model):
    """
    This model is for those who write the blogs
    """
    first_name = models.CharField(max_length=15, help_text="Enter your first name")
    last_name = models.CharField(max_length=15, help_text="Enter your last name")
    bio = models.TextField(max_length=500, help_text="Your brief history")

    class Meta:
        ordering = ["-first_name"]

    def get_absolute_url(self):
        return reverse("story:blogger-detail", args=[str(self.id)])

    def __str__(self):
        """
        String representation of the blogger object
        :return:
        """
        return "{0}, {1}".format(self.last_name, self.first_name)


class BlogPost(models.Model):
    """
    Blog post by the authors
    """
    title = models.CharField(max_length=225, help_text="Enter the title of your blog")
    blogger = models.ForeignKey(Blogger, on_delete=models.CASCADE)
    description = models.TextField(max_length=2000, help_text="Write your article")
    post_date = models.DateTimeField("date posted", default=timezone.now)

    class Meta:
        """To order the post by newest first"""
        ordering = ["-post_date"]

    def get_absolute_url(self):
        """Returns the url to access a particular instance of model"""
        return reverse("story:blog-detail", args=[str(self.id)])

    def __str__(self):
        """
        String representation of the blog post object
        :return:
        """
        return self.title


class Comment(models.Model):
    """
    This is model for comment a each specific blog post
    """
    author = models.ForeignKey(Blogger, on_delete=models.CASCADE)
    comment = models.TextField(max_length=500, help_text="Enter your comments")
    post_time = models.DateTimeField("time posted", default=timezone.now)
    blog = models.ForeignKey(BlogPost, on_delete=models.CASCADE)

    class Meta:
        ordering = ["-post_time"]

    def get_absolute_url(self):
        """Returns the url to access a particular instance of model"""
        return reverse("story:blog-detail", args=[str(self.id)])

    def __str__(self):
        """String representation of the comments object"""
        return self.comment

mozilla_blog/story/views.py
from django.shortcuts import render
from django.views import generic
from django.urls import reverse
from .models import Blogger, BlogPost, Comment


def index(request):
    return render(request, "story/index.html")


class BlogPostListView(generic.ListView):
    model = BlogPost
    # context_object_name = "my_blog_list"
    # queryset = BlogPost.objects.all()
    template_name = "story/blog_list.html"


class BlogPostDetailView(generic.DetailView):
    model = BlogPost
    context_object_name = "my_blog_detail"
    template_name = "story/blog_detail.html"


class BloggerListView(generic.ListView):
    model = Blogger
    template_name = "story/blogger_list.html"


class BloggerDetailView(generic.DetailView):
    model = Blogger
    template_name = "story/blogger_detail.html"

mozilla_blog/story/templates/story/base_generic.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible" />
    <meta content="width=device-width, initial-scale=1, maximum-scale=2, user-scalable=no" name="viewport" />
    <meta content="blog" name="description" />
    <meta content="blog" name="keywords" />
    <meta content="PPType" name="author" />
    {% block title %}
        <title>Mozilla Blog </title>
    {% endblock %}
    <link href="{% static 'story/css/semantic-ui/semantic.min.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'story/css/default.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'story/css/style.css' %}" rel="stylesheet" type="text/css" />
    <script src="{%  static 'story/js/jquery.min.js' %}"></script>
</head>
<body>
{% block menu %}
    <div class="ui borderless fixed blue inverted pointing menu">
        <div class="ui container">
            <a class="header active item" href="{% url 'story:index' %}">Home</a>
            <a class="item" href="{% url 'story:blogs' %}">All Blogs</a>
            <a class="item" href="{% url 'story:bloggers' %}">All Bloggers</a>
            <a href="" class="item">All Comments</a>
        </div>
    </div>
{% endblock %}

<div class="ui grid container">
    {% block page_header %}
        <div class="row" id="page-header">
            <div class="ui basic segment">
                <h1 class="ui sub header">
                    The Mozilla Blog
                </h1>
                <span>Indecision is the thief of opportunity.</span>
            </div>
        </div>
    {% endblock %}
    <div class="row" id="article">
        <div class="eleven wide column">
            {% block content %}

            {% endblock %}
        </div>
        {% block side_bar %}
            <div class="four wide right floated column">
                <div class="ui secondary segment">
                    <h4 class="ui header">
                        About
                    </h4>
                    <p>
                        Etiam porta <i>sem malesuada magna mollis euismod</i>. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.
                    </p>
                </div>
                <h4 class="ui header">
                    Sub Menu
                </h4>
                <div class="ui list">
                    <a class="item" href="{% url 'story:index' %}">Home</a>
                    <a class="item" href="{% url 'story:blogs' %}">All blogs</a>
                    <a class="item" href="{% url 'story:bloggers' %}">All bloggers</a>
                </div>
                <h4 class="ui header">
                    Elsewhere
                </h4>
                <div class="ui list">
                    <h4 href="" class="item">
                        <div class="content">
                            <div class="header">Tom Tom</div>
                            User
                        </div>
                    </h4>

                </div>
            </div>
        {% endblock %}

    </div>

</div>


    <div class="ui footer secondary segment">
        <div class="ui center aligned container">
            <p>
                Blog template built for Semantic-UI by <a href="">@Semantic-UI-Forest</a>.
            </p>
            <a href="">Back to top</a>
        </div>
    </div>

</html>

mozilla_blog/story/templates/story/blog_detail.html
{% extends "story/base_generic.html" %}

{% block content %}

    {% if my_blog_detail %}
        <h2 class="ui teal dividing header">
            <i class="pencil alternate icon"></i>

            <div class="content">
                {{ my_blog_detail.title }}
                <div class="sub header">Published on: {{ my_blog_detail.post_date }}</div>
                <div class="sub header">By <a href="{{ my_blog_detail.blogger.get_absolute_url }}">{{ my_blog_detail.blogger }}</a></div>
            </div>
        </h2>
        <div class="ui basic segment">
            <p>{{ my_blog_detail.description }}</p>
        </div>
    {% endif %}
{% endblock %}

mozilla_blog/story/templates/story/blog_list.html
{% extends "story/base_generic.html" %}

{% block content %}

        <div class="ui very relaxed middle aligned divided list">
            {% if blogpost_list %}
                {% for my_blog in blogpost_list %}
                    <div class="item">
                        <div class="right floated content">
                            <h4 class="ui teal header">
                                <a href="{{ my_blog.blogger.get_absolute_url }}">{{ my_blog.blogger }}</a>
                            </h4>
                        </div>
                        <div class="content">
                            <h4><a href="{{ my_blog.get_absolute_url }}" class="header">{{ my_blog.title }}</a></h4>
                            <div class="description">{{ my_blog.post_date }}.</div>
                        </div>
                    </div>
                {% endfor %}
            {% endif %}
        </div>

{% endblock %}

mozilla_blog/story/templates/story/blogger_detail.html
{% extends "story/base_generic.html" %}

{% block content %}

    {% if blogger %}
        <h2 class="ui purple header">
            <i class="user icon"></i>

            <div class="content">
                {{ blogger.last_name }} {{ blogger.first_name }}
            </div>
        </h2>
        <div class="ui basic segment">
            <h3 class="ui dividing header">Bio:</h3>
            <p>{{ blogger.bio }}</p>
        </div>
        <div class="ui basic segment">
            <h3 class="ui dividing header">Comments:</h3>
            <div class="ui very relaxed divided list">
            {% for comm in blogger.comment_set.all %}
                    <div class="item">
                        <div class="content">
                            <a class="header" href="{{ comm.blog.get_absolute_url }}">{{ comm.blog }}</a>
                            <div class="description">{{ comm.comment }}</div>
                        </div>
                    </div>

            {% endfor %}
             </div>
        </div>

    {% endif %}
{% endblock %}

mozilla_blog/story/templates/story/blogger_list.html
{% extends "story/base_generic.html" %}

{% block content %}
    <div class="ui very relaxed middle aligned divided list">
        {% if blogger_list %}
            {% for blogger in blogger_list %}
                <div class="item">
                    <div class="content">
                        <h4><a href="{{ blogger.get_absolute_url }}" class="header">{{ blogger.first_name }} {{ blogger.last_name }}</a></h4>
{#                        <div class="description">{{ my_blog.post_date }}.</div>#}
                    </div>
                </div>
            {% endfor %}
        {% endif %}
    </div>

{% endblock %}

mozilla_blog/story/templates/story/index.html
{% extends "story/base_generic.html" %}

{% block content %}

        <h2 class="ui icon blue header">
            <i class="chess icon"></i>
            <div class="content">
                Sample blog post
                <div class="sub header">Manage your blogs account preferences.</div>
            </div>
        </h2>
        <span>March 6, 2017 by <a href="">Jack</a></span>
        <div class="ui hidden divider"></div>
        <p>
            This blog post shows a few different types of content that's supported and styled with Semantic-UI. Basic typesetting, list, and code are all supported.
        </p>
        <div class="ui divider"></div>

        <div class="ui relaxed divided list">
            <div class="item">
                <div class="right floated content">
                    <div class="header">Steve Jobes</div>
                </div>
                <i class="large sticky note outline middle aligned icon"></i>
                <div class="content">
                    <a class="header">Blog Title </a>
                    <div class="description">Updated 10 mins ago</div>
                </div>
            </div>
            <div class="item">
                <div class="right floated content">
                    <div class="header">Steve Jobes</div>
                </div>
                <i class="large sticky note outline middle aligned icon"></i>
                <div class="content">
                    <a class="header">Blog Title -Docs</a>
                    <div class="description">Updated 22 mins ago</div>
                </div>
            </div>
            <div class="item">
                <div class="right floated content">
                    <div class="header">Steve Jobes</div>
                </div>
                <i class="large sticky note outline middle aligned icon"></i>
                <div class="content">
                    <a class="header">Blog Title -Meteor</a>
                    <div class="description">Updated 34 mins ago</div>
                </div>
            </div>

        </div>
        <div class="ui basic segment">
            <div class="ui basic circular huge button">
                <a href="">Previous</a>
            </div>
            <div class="ui basic circular huge button">
                <a href="">Next</a>
            </div>
        </div>


{% endblock %}